{{- if and .Values.global.imagePullSecret.name .Values.global.imagePullSecret.dockerconfigjson }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.imagePullSecret.name | quote }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.global.imagePullSecret.dockerconfigjson | quote }}
{{- end }}
