enabled: true # todo: change the default to false

global:
  cxLogging:
    enabled: false
    clusterName: ""
    apiKey: ""
    ingressUrl: https://ingress.eu2.coralogix.com/

nameOverride: ~
fullnameOverride: ~

image:
  registry: 473301030746.dkr.ecr.us-west-2.amazonaws.com/zesty-k8s/pod-placement
  pullPolicy: Always
  tag: 223344

# -- (array) Image pull secrets for private registries
# imagePullSecrets: []

serviceAccount:
  create: true
  annotations: {}

replicaCount: 2

webhook:
  port: 9443
  failurePolicy: Ignore
  timeoutSeconds: 5
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

certificate:
  provider: "cert-manager"

service:
  portName: https

rbac:
  create: true

podAnnotations: {}
podLabels: {}

podDisruptionBudget:
  enabled: true
  minAvailable: 1

cxLogging:
  enabled: false
  clusterName: ""
  apiKey: ""
  ingressUrl: https://ingress.eu2.coralogix.com/
