enabled: true # todo: change the default to false

global:
  cxLogging:
    enabled: false
    clusterName: ""
    apiKey: ""
    ingressUrl: https://ingress.eu2.coralogix.com/

nameOverride: ~
fullnameOverride: ~

image:
  registry: 473301030746.dkr.ecr.us-west-2.amazonaws.com/zesty-k8s/pod-placement
  pullPolicy: Always
  tag: 223344

# -- (array) Image pull secrets for private registries
imagePullSecrets: []

serviceAccount:
  create: true
  name: ""
  annotations: {}

replicaCount: 2

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

service:
  portName: https
  port: 443
  targetPortName: https
  type: ClusterIP

ports:
  https:
    name: https
    containerPort: 9443
    protocol: TCP
  metrics:
    name: metrics
    containerPort: 8080
    protocol: TCP
  health:
    name: healthz
    containerPort: 8081
    protocol: TCP

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}

podAnnotations: {}
podLabels: {}

extraArgs: []
env: []
envFrom: []

extraVolumes: []
extraVolumeMounts: []

probes:
  readiness:
    httpGet:
      path: /ready
      port: healthz
    initialDelaySeconds: 30
    periodSeconds: 10
  liveness:
    httpGet:
      path: /health
      port: healthz
    initialDelaySeconds: 30
    periodSeconds: 10

podDisruptionBudget:
  enabled: true
  minAvailable: 1
  maxUnavailable: ~

rbac:
  create: true

cxLogging:
  enabled: false
  clusterName: ""
  apiKey: ""
  ingressUrl: https://ingress.eu2.coralogix.com/
