{{- if and .Values.enabled .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kompass-pod-placement.fullname" . }}-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kompass-pod-placement.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
spec:  
  ports:
    - name: webhook
      port: {{ .Values.webhook.port }}
      targetPort: webhook
      protocol: TCP
    - name: metrics
      port: 8080
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "kompass-pod-placement.webhook.selectorLabels" . | nindent 4 }}
  type: ClusterIP
{{- end }}
