{{- if and .Values.enabled (eq .Values.certificate.provider "cert-manager") }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "kompass-pod-placement.fullname" . }}-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kompass-pod-placement.labels" . | nindent 4 }}
spec:
  secretName: {{ include "kompass-pod-placement.fullname" . }}-webhook-cert
  dnsNames:
    - {{ include "kompass-pod-placement.fullname" . }}
    - {{ include "kompass-pod-placement.fullname" . }}.{{ .Release.Namespace }}.svc
    - {{ include "kompass-pod-placement.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: ClusterIssuer
    {{ if .Values.global }}
    name: {{ .Values.global.clusterIssuerName }}
    {{ end }}
{{- end }}
