{{- if and .Values.enabled .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kompass-pod-placement.roleName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kompass-pod-placement.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kompass-pod-placement.roleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kompass-pod-placement.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
