{{- if and .Values.enabled .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kompass-pod-placement.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kompass-pod-placement.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
